services:
    kasimi.postnumbers.listener:
        class: kasimi\postnumbers\event\listener
        arguments:
            - '@user'
            - '@config'
            - '@request'
            - '@template'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
